apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeployment
   labels:
       app: myappdeployment
       tier: frontend
spec:
   replicas: 3
   selector:
      matchLabels:
         name: mypoddeployment
   template:
      metadata:
       name: myapp-deployment
       labels:
          name: mypoddeployment
      spec:
         containers:
             - name: nginx
               image: nginx
