apiVersion: v1
kind: ReplicationController
metadata:
    name: mycontroller
    labels:
       app: myreplicacontroller
       tier: front-end
spec:
    replicas: 3
    template:
       metadata:
         name: myapp-contollerpod
         labels:
            app: mycontrollerpod
       spec:
         containers:
              - name: nginx
                image: nginx
