---
- name: create user in client servers
  hosts: dev
  become: true
  tasks:
          - name: creating admin user
            user:
                    name: admin
                    password: admin
                    groups: docker, tcpdump
                    state: present
                    shell: /bin/bash
                    createhome: yes
                    home: /home/admin
